apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-pv-claim${srv}
  namespace: simple-fio
spec:
  storageClassName: ${storage_type}
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${storage}Gi
