apiVersion: v1
kind: Pod
metadata:
  name: fio-client
  namespace: simple-fio
spec:
  containers:
    - image: quay.io/abose/fio:latest
      name: fio-client
      command: ["/bin/sh", "-c"]
      args: 
        - "echo *********Prefill**************;
            /usr/bin/fio --output=/tmp/prefill_output.log ${fio_args_prefill};
            sleep 10;
            grep -A6 \"All clients\" /tmp/prefill_output.log;
	    sleep 60;
	for itr in $(seq 1 ${sample});
        	do
            	echo *********Fio_Job_Sample**************;
		echo $itr;
            	/usr/bin/fio --output=/tmp/output.log ${fio_args_job}; 
            	sleep 10; 
            	grep -A6 \"All clients\" /tmp/output.log;
            	sleep 50; 
	done;
          "
  restartPolicy: Never
