apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-data-pvc
  namespace: simple-fio
spec:
  storageClassName: ${sc_type}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
