apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-pv-claim${srv}
  namespace: simple-fio
spec:
<<<<<<< HEAD
  storageClassName: ${storage_type}
=======
  storageClassName: ${sc}
>>>>>>> source/main
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${storage}Gi
