apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-pv-claim${srv}
  namespace: simple-fio
spec:
  storageClassName: ${sc}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${storage}Gi
