apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-pv-claim1
spec:
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
