apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-pv-claim${srv}
spec:
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${storage}Gi
