#!/bin/bash

# Script to separate normal logs and JSON data into different files
# Generated by Claude Sonnet AI 
# Usage: ./split_logs.sh <input_file>

# Check if input file is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 <input_file>"
    echo "Example: $0 smmary.json"
    exit 1
fi

INPUT_FILE="$1"
SUMMARY_LOG="summary.log"
SUMMARY_JSON="summary.json"

# Check if input file exists
if [ ! -f "$INPUT_FILE" ]; then
    echo "Error: Input file '$INPUT_FILE' not found!"
    exit 1
fi

cp $INPUT_FILE stage.log
INPUT_FILE="stage.log"

# Find the line number where JSON starts (looking for the fio version pattern)
# First try to find the specific fio version pattern, then find the opening brace before it
FIO_VERSION_LINE=$(grep -n '"fio version"' "$INPUT_FILE" | head -1 | cut -d: -f1)

if [ -n "$FIO_VERSION_LINE" ]; then
    # Look for the opening brace before the fio version line
    JSON_START_LINE=$(head -n "$FIO_VERSION_LINE" "$INPUT_FILE" | grep -n '^\s*{\s*$' | tail -1 | cut -d: -f1)
fi

# If fio version approach didn't work, look for opening brace that starts JSON
if [ -z "$JSON_START_LINE" ]; then
    JSON_START_LINE=$(grep -n '^\s*{\s*$' "$INPUT_FILE" | head -1 | cut -d: -f1)
fi

if [ -z "$JSON_START_LINE" ]; then
    echo "Error: Could not find JSON start pattern in the file!"
    exit 1
fi


# Calculate the line before JSON starts for the normal logs
NORMAL_LOG_END_LINE=$((JSON_START_LINE - 1))

# Extract normal logs (first part) to summary.log
if [ $NORMAL_LOG_END_LINE -gt 0 ]; then
    head -n "$NORMAL_LOG_END_LINE" "$INPUT_FILE" > "$SUMMARY_LOG"
else
    touch "$SUMMARY_LOG"
fi

# Extract JSON data (second part) to summary.json
tail -n +"$JSON_START_LINE" "$INPUT_FILE" > "$SUMMARY_JSON"
rm -f $INPUT_FILE

